//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagment.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int GuestID { get; set; }
        public System.DateTime BookDate { get; set; }
        public int Duration { get; set; }
        public int Id_room { get; set; }
        public double Amount { get; set; }
        public int HotelAdminID { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual HotelAdmin HotelAdmin { get; set; }
        public virtual Room Room { get; set; }
    }
}
